# Generated by Django 6.0.2 on 2026-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_workout_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayexercise',
            name='superset_group',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Группа суперсета'),
        ),
    ]
