# Generated by Django 6.0.2 on 2026-03-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_dayexercise_superset_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Вес (кг)')),
                ('recorded_date', models.DateField(verbose_name='Дата записи')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_weights', to='programs.exercise', verbose_name='Упражнение')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_weights', to='programs.week', verbose_name='Неделя')),
            ],
            options={
                'verbose_name': 'Вес подсобки',
                'verbose_name_plural': 'Веса подсобок',
                'ordering': ['-recorded_date'],
                'unique_together': {('telegram_id', 'exercise', 'recorded_date')},
            },
        ),
    ]
