# Generated by Django 6.0.2 on 2026-04-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_userprofile_telegram_photo_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutcompletion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutcompletion',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер недели'),
        ),
        migrations.AddField(
            model_name='workoutcompletion',
            name='weekday',
            field=models.CharField(blank=True, choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], max_length=3, null=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='day',
            name='weekday',
            field=models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], max_length=3, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='workoutcompletion',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='programs.day', verbose_name='День'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutcompletion',
            unique_together={('telegram_id', 'week_number', 'weekday')},
        ),
        migrations.CreateModel(
            name='ProgramSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('payload', models.JSONField(default=dict, verbose_name='Снапшот программы')),
                ('source_snapshot_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Исходная версия')),
            ],
            options={
                'verbose_name': 'Снапшот программы',
                'verbose_name_plural': 'Снапшоты программы',
                'ordering': ['-version'],
                'unique_together': {('telegram_id', 'version')},
            },
        ),
    ]
