# Generated by Django 6.0.2 on 2026-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_alter_workoutcompletion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsnapshot',
            name='commit_message',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий к версии'),
        ),
    ]
