# Generated by Django 6.0.2 on 2026-04-18 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_program_specific_one_rep_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('program_payload', models.JSONField(default=dict, verbose_name='Снапшот программы')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало цикла')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение цикла')),
                ('completion_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина завершения')),
                ('completion_feeling', models.TextField(blank=True, default='', verbose_name='Ощущения от программы')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_cycles', to='programs.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Тренировочный цикл',
                'verbose_name_plural': 'Тренировочные циклы',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('scope', models.CharField(choices=[('ONLY_HERE', 'Только здесь'), ('CURRENT_CYCLE', 'До конца текущего цикла'), ('FUTURE_CYCLES', 'Во всех будущих циклах')], max_length=20, verbose_name='Область действия')),
                ('action', models.CharField(choices=[('DELETE', 'Удалить'), ('REPLACE', 'Заменить')], max_length=10, verbose_name='Действие')),
                ('slot_key', models.CharField(max_length=100, verbose_name='Ключ позиции')),
                ('week_number', models.PositiveIntegerField(verbose_name='Номер недели')),
                ('weekday', models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница'), ('SAT', 'Суббота'), ('SUN', 'Воскресенье')], max_length=3, verbose_name='День недели')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Причина адаптации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('original_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_program_adaptations', to='programs.exercise', verbose_name='Исходное упражнение')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptations', to='programs.program', verbose_name='Программа')),
                ('replacement_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_program_adaptations', to='programs.exercise', verbose_name='Заменяющее упражнение')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptations', to='programs.trainingcycle', verbose_name='Тренировочный цикл')),
            ],
            options={
                'verbose_name': 'Адаптация программы',
                'verbose_name_plural': 'Адаптации программы',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='workoutcompletion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutcompletion',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='programs.trainingcycle', verbose_name='Тренировочный цикл'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutcompletion',
            unique_together={('cycle', 'week_number', 'weekday')},
        ),
        migrations.CreateModel(
            name='CycleOneRepMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='Подпись')),
                ('value', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Разовый максимум (кг)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_one_rep_max_values', to='programs.exercise', verbose_name='Упражнение 1ПМ')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_rep_max_values', to='programs.trainingcycle', verbose_name='Тренировочный цикл')),
            ],
            options={
                'verbose_name': '1ПМ тренировочного цикла',
                'verbose_name_plural': '1ПМ тренировочных циклов',
                'ordering': ['cycle_id', 'exercise_id'],
                'unique_together': {('cycle', 'exercise')},
            },
        ),
    ]
