from django.urls import path

from .views import (
    AccessoryWeightHistoryView,
    AccessoryWeightLatestView,
    AccessoryWeightView,
    AuthSessionView,
    CompletionDetailView,
    CompletionListView,
    ExerciseCatalogView,
    LogoutView,
    OneRepMaxView,
    ProgramListView,
    ProgramCurrentView,
    ProgramHistoryDetailView,
    ProgramHistoryListView,
    ProgramAdaptationListCreateView,
    ProgramOriginalView,
    ProgramSelectionView,
    ProgramSnapshotCreateView,
    TelegramLoginView,
    TrainingCycleActiveView,
    TrainingCycleFinishView,
    TrainingCycleHistoryView,
    TrainingCycleStartView,
    WeekDetailView,
    WeekListView,
)

urlpatterns = [
    path("auth/session/", AuthSessionView.as_view(), name="auth-session"),
    path("auth/telegram/", TelegramLoginView.as_view(), name="auth-telegram"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("weeks/", WeekListView.as_view(), name="week-list"),
    path("weeks/<int:number>/", WeekDetailView.as_view(), name="week-detail"),
    path("programs/", ProgramListView.as_view(), name="program-list"),
    path("programs/selected/", ProgramSelectionView.as_view(), name="program-selection"),
    path("program/", ProgramCurrentView.as_view(), name="program-current"),
    path("program/original/", ProgramOriginalView.as_view(), name="program-original"),
    path("program/snapshots/", ProgramSnapshotCreateView.as_view(), name="program-snapshot-create"),
    path("program/history/", ProgramHistoryListView.as_view(), name="program-history-list"),
    path("program/history/<int:version>/", ProgramHistoryDetailView.as_view(), name="program-history-detail"),
    path("program/adaptations/", ProgramAdaptationListCreateView.as_view(), name="program-adaptation-list-create"),
    path("exercises/", ExerciseCatalogView.as_view(), name="exercise-catalog"),
    path("one-rep-max/", OneRepMaxView.as_view(), name="one-rep-max"),
    path("completions/", CompletionListView.as_view(), name="completion-list"),
    path("completions/<int:week_number>/<str:weekday>/", CompletionDetailView.as_view(), name="completion-detail"),
    path("training-cycle/active/", TrainingCycleActiveView.as_view(), name="training-cycle-active"),
    path("training-cycle/start/", TrainingCycleStartView.as_view(), name="training-cycle-start"),
    path("training-cycle/finish/", TrainingCycleFinishView.as_view(), name="training-cycle-finish"),
    path("training-cycle/history/", TrainingCycleHistoryView.as_view(), name="training-cycle-history"),
    path("accessory-weights/latest/", AccessoryWeightLatestView.as_view(), name="accessory-weight-latest"),
    path("accessory-weights/<int:exercise_id>/", AccessoryWeightView.as_view(), name="accessory-weight-upsert"),
    path("accessory-weights/<int:exercise_id>/history/", AccessoryWeightHistoryView.as_view(), name="accessory-weight-history"),
]
